# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
# relative_permalinks: true


# Setup
title:            Bridging Futures
tagline:          '___'
description:      'UK-based, Ukrainian-led non-profit working to help build a pathway to long-term settlement in the UK for people on the Ukraine visa schemes.'
url:              https://bridgingfutures.uk
baseurl:          /

author:
  name:           'Bridging Futures'
  url:            https://bridgingfutures.uk

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
